config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :favarites

  root to: 'reports#index'
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_up', as: :users_sign_up
    post 'users/admin_create' => 'users#admin_create', :as => 'user_admin_create'
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users do
    collection do
      get 'with_progresses'
    end
  end

  resources :reports do
    collection do
      get 'tagcount'
      get 'tagcloud'
    end
  end
  resources :reports
  get 'reports/download/:id'=> 'reports#download', as: :donwload
  get 'reports/:id/slide'=> 'reports#slide', as: :slide

  resources :attachments
  resources :images
  get 'images/show/:id'=> 'images#show', as: :show_image
  resources :comments do
    collection do
      get 'for_user/:user_id' => 'comments#for_user', as: :for_user
      get 'back_for_user/:user_id' => 'comments#back_for_user', as: :back_for_user
    end
  end
  resources :comments
  resources :progresses do
    collection do
      get 'for_user/:user_id' => 'progresses#for_user', as: :for_user
    end
  end
  resources :progresses
  post 'notices/upsert' => 'notices#upsert', as: :upsert
  resources :notices

end

app/models/favarite.rb
class Favarite < ActiveRecord::Base
  belongs_to :report

  validates :user_id,
  uniqueness: {
    message: "user_id、report_idが同じ組み合わせのレコードが既に存在します。",
    scope: [:report_id]
  }
end

app/controllers/favarites_controller.rb
class FavaritesController < ApplicationController
  before_action :set_favarite, only: [:show, :edit, :update, :destroy]

  # GET /favarites
  # GET /favarites.json
  def index
    @favarites = Favarite.where(user_id: current_user.id).joins(:report)
  end

  # POST /favarites
  # POST /favarites.json
  def create
    @favarite = Favarite.new(favarite_params)

    respond_to do |format|
      if @favarite.save
        format.html { redirect_to @favarite, notice: 'Favarite was successfully created.' }
        format.json { render :show, status: :created, location: @favarite }
      else
        format.html { render :new }
        format.json { render json: @favarite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favarites/1
  # DELETE /favarites/1.json
  def destroy
    @favarite.destroy
    respond_to do |format|
      format.html { redirect_to favarites_url, notice: 'Favarite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favarite
      @favarite = Favarite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favarite_params
      params.require(:favarite).permit(:user_id, :report_id)
    end
end

app/helpers/favarites_helper.rb
module FavaritesHelper
end

app/views/favarites/_form.html.erb
<%= form_for(@favarite) do |f| %>
  <% if @favarite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favarite.errors.count, "error") %> prohibited this favarite from being saved:</h2>

      <ul>
      <% @favarite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field" hidden>
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="field">
    <%= f.label :report_id %><br>
    <%= f.number_field :report_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favarites/edit.html.erb
<h1>Editing Favarite</h1>

<%= render 'form' %>

<%= link_to 'Show', @favarite %> |
<%= link_to 'Back', favarites_path %>

app/views/favarites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>お気に入り</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>タグ</th>
      <th>タイトル</th>
      <th>削除</th>
    </tr>
  </thead>

  <tbody>
    <% @favarites.each do |favarite| %>
      <tr>
        <td><%= favarite.report.id %></td>
        <td><%= favarite.report.tag %></td>
        <td><%= link_to favarite.report.title, favarite.report %></td>
        <td><%= link_to '削除', favarite, method: :delete, data: { confirm: 'お気に入りから削除しますか?' }, class: 'btn btn-warning' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="bottom-action">
  <%= link_to '戻る', reports_path, class: "btn btn-default pull-left margin-right-md" %>
</div>

app/views/favarites/new.html.erb
<h1>New Favarite</h1>

<%= render 'form' %>

<%= link_to 'Back', favarites_path %>

app/views/favarites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favarite.user_id %>
</p>

<p>
  <strong>Report:</strong>
  <%= @favarite.report_id %>
</p>

<%= link_to 'Edit', edit_favarite_path(@favarite) %> |
<%= link_to 'Back', favarites_path %>