config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :favarites

  root to: 'reports#index'
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_up', as: :users_sign_up
    post 'users/admin_create' => 'users#admin_create', :as => 'user_admin_create'
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users do
    collection do
      get 'with_progresses'
    end
  end

  resources :reports do
    collection do
      get 'tagcount'
      get 'tagcloud'
    end
  end
  resources :reports
  get 'reports/download/:id'=> 'reports#download', as: :donwload
  get 'reports/:id/slide'=> 'reports#slide', as: :slide

  resources :attachments
  resources :images
  get 'images/show/:id'=> 'images#show', as: :show_image
  resources :comments do
    collection do
      get 'for_user/:user_id' => 'comments#for_user', as: :for_user
      get 'back_for_user/:user_id' => 'comments#back_for_user', as: :back_for_user
    end
  end
  resources :comments
  resources :progresses do
    collection do
      get 'for_user/:user_id' => 'progresses#for_user', as: :for_user
    end
  end
  resources :progresses
  post 'notices/upsert' => 'notices#upsert', as: :upsert
  resources :notices

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, #:registerable
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :progresses
  has_many :images

  def self.with_progress_points
    select('users.id, users.name, p.point, p.updated_at')
    .joins('left outer join (SELECT reports.user_id, progresses.point, progresses.updated_at FROM REPORTS left outer join PROGRESSES on reports.id = progresses.report_id) AS p on users.id = p.user_id')
    .order('users.id, p.updated_at')
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_action :set_user, only: [:destroy, :create]

  # GET /users
  # GET /users.json
  def index
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def with_progresses
    @user_with_progresses = User.with_progress_points
    render :json => @user_with_progresses.to_json
  end

  def sign_up
    if current_user.try(:admin?)
      @user = User.new
    else
      redirect_to reports_path
    end
  end

  def admin_create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        format.html { redirect_to reports_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :sign_up }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :created_at, :updated_at, :admin)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/sign_up.html.erb
<h2>サインアップ</h2>

<%= form_for(resource, as: resource_name, url: user_admin_create_path) do |f| %>
<%= devise_error_messages! %>

<div class="form-group">
  <%= f.label :name %><br/>
  <%= f.text_field :name, autofocus: true, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :email %><br/>
  <%= f.email_field :email, :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <% if @validatable %>
  <em>(<%= @minimum_password_length %>
    characters minimum)</em>
  <% end %><br/>
  <%= f.password_field :password, autocomplete: "off", :class => 'form-control' %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %><br/>
  <%= f.password_field :password_confirmation, autocomplete: "off", :class => 'form-control' %>
</div>

<div class="actions">
  <%= f.submit "サインアップ", :class => 'btn btn-primary' %>
</div>
<% end %>