config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :favarites

  root to: 'reports#index'
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_up', as: :users_sign_up
    post 'users/admin_create' => 'users#admin_create', :as => 'user_admin_create'
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users do
    collection do
      get 'with_progresses'
    end
  end

  resources :reports do
    collection do
      get 'tagcount'
      get 'tagcloud'
    end
  end
  resources :reports
  get 'reports/download/:id'=> 'reports#download', as: :donwload
  get 'reports/:id/slide'=> 'reports#slide', as: :slide

  resources :attachments
  resources :images
  get 'images/show/:id'=> 'images#show', as: :show_image
  resources :comments do
    collection do
      get 'for_user/:user_id' => 'comments#for_user', as: :for_user
      get 'back_for_user/:user_id' => 'comments#back_for_user', as: :back_for_user
    end
  end
  resources :comments
  resources :progresses do
    collection do
      get 'for_user/:user_id' => 'progresses#for_user', as: :for_user
    end
  end
  resources :progresses
  post 'notices/upsert' => 'notices#upsert', as: :upsert
  resources :notices

end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  has_many :progresses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :attachments, dependent: :destroy
  has_many :favarite, dependent: :destroy

  validates :title, presence: true
  validates :content, presence: true

  def self.with_progress_points_and_number_of_comments
    joins('left outer join (SELECT SUM(point) AS progress_points, report_id FROM PROGRESSES GROUP BY report_id) AS p on reports.id = p.report_id')
      .joins('left outer join (SELECT COUNT(*) AS number_of_comments, report_id FROM COMMENTS GROUP BY report_id) AS c on reports.id = c.report_id')
      .select('reports.*, COALESCE(progress_points, 0) AS progress_points, COALESCE(number_of_comments, 0) AS number_of_comments')
  end

  def self.index_default_order
    # 基本は、1:更新日付降順、2:成長ポイント降順, 3:コメント数降順, 4:更新日時降順 でソート（※日付と日時の違いに注意）
    order('DATE(updated_at) desc').order('progress_points desc').order('number_of_comments desc').order('updated_at desc')
  end

  def self.progress_points_by_user_this_month
    select('users.name AS user_name, SUM(progresses.point) AS progress_points')
      .joins(:progresses)
      .joins(:user)
      .where('progresses.updated_at': Time.now.beginning_of_month...Time.now.end_of_month)
      .group('users.id')
      .order('progress_points desc')
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy, :progress, :slide]
  before_action :set_user_with_progress_points, only: :index
  before_action :set_attachment, only: :download
  before_action :check_current_users_report, only: [:edit, :update, :destroy]

  def download
    send_data @attachment.file, filename: @attachment.name
  end

  # GET /reports
  # GET /reports.json
  def index
    # 検索条件の指定がないときは、デフォルトで7日前からの検索にする
    # index.html.erbの初期値との整合性に注意
    if params[:q].nil?
      params[:q] = {
        # updated_at_gteq: 7.day.ago.strftime('%Y-%m-%d'),
        updated_at_lteq_end_of_day: 0.day.ago.strftime('%Y-%m-%d')
      }
    end

    @base = Report.page(params[:page]).with_progress_points_and_number_of_comments
    # ransakで検索
    # https://github.com/activerecord-hackery/ransack
    @q = @base.ransack(params[:q])
    # left joinしたprogress_pointsはransakでは直接扱えないため、個別対応
    if params[:q][:s].nil? || !params[:q][:s].include?('progress_points')
      @reports = @q.result.index_default_order
    else
      @reports = @q.result.order(params[:q][:s])
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # GET /reports/1/slide
  def slide
    render :slide, layout: 'slide'
  end

  # POST /reports
  # POST /reports.json
  def create
    respond_to do |format|
      begin
        Report.transaction do
          @report = Report.new(report_params)
          @report.save!
          create_attachments!(attachment_params(@report.id))
        end
        format.html { redirect_to action: 'index', notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      rescue
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      begin
        Report.transaction do
          @report.update!(report_params)
          @report.touch
          create_attachments!(attachment_params(params[:id]))
        end
        format.html { redirect_to reports_url, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      rescue => e
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def tagcloud
  end

  def tagcount
    # 複数タグを半角スペース区切りで入力している場合があるのでそれを分離
    tags = Report.select(:tag).map(&:tag)
    all_tags = []
    tags.each { |tag| all_tags.concat(tag.split(' ')) }

    uniq_tags = all_tags.uniq
    render json: uniq_tags.map { |tag| { text: tag, weight: all_tags.count(tag) } }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  def set_user_with_progress_points
    @user_with_progress_points = Report.progress_points_by_user_this_month
  end

  def set_attachment
    @attachment = Attachment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:title, :tag, :content, :user_id, :created_at, :updated_at, :collaboration)
  end

  def attachment_params(report_id)
    params.require(:report).permit(:id, :attachments)

    attachments = []
    unless params[:report][:attachments].nil?
      params[:report][:attachments].each do |a|
        attachments.push(file: a.read, name: a.original_filename, report_id: report_id)
      end
    end
    attachments
  end

  def create_attachments!(data)
    # リクエストのattachmentsが空でなければcreate
    unless params[:report][:attachments].nil?
      data.each do |a|
        Attachment.create!(a)
      end
    end
  end

  def check_current_users_report
    puts @report.user_id
    redirect_to(root_path) unless current_user.id == @report.user_id || @report.collaboration == 1
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<div class="well well-sm">
  内容は<%= link_to 'Markdown記法', 'http://ja.wikipedia.org/wiki/Markdown', target: '_blank' %>で入力してください。<%= link_to 'GitHub Flavored Markdown', 'https://help.github.com/articles/github-flavored-markdown/', target: '_blank' %>も使えます。タグを複数設定する場合は半角スペースで区切ってください。<br>
  TableはExcelで作ってからコピーして、<%= link_to 'Tables Generator', 'http://www.tablesgenerator.com/markdown_tables', target: '_blank' %>の[File] => [Paste table data...]すると、簡単にきれいなTableのMarkdownがつくれます。<br>
  '---'がスライドモードのスライドの区切りになります。テンプレートのルールは<%= link_to 'こちら', '#', :id => 'templateRule' %>。
</div>

<%= form_for(@report) do |f| %>
<div class="row">
  <div class="col-md-6">
    <!-- <% if name == '作成' %>
    <%= collection_select :templates, :title, Report.where('tag LIKE ?', '%テンプレート%'), :id, :title, {:prompt => "テンプレート選択"}, class: 'form-control margin-bottom-md js-template-select' %>
    <% end %> -->
    <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %>
        prohibited this report from being saved:</h2>

      <ul>
        <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

    <!-- <div class="field form-group">
      <%= f.text_field :tag, class: "form-control typeahead", placeholder:"タグ", autocomplete: "off" %>
    </div> -->
    <div class="field form-group">
      <%= f.text_field :title, id: "title", class: "form-control", placeholder:"タイトル" %>
    </div>
    <div class="field form-group margin-bottom-0">
      <%= f.text_area :content, id: "content", class: "form-control", placeholder:"内容", rows: 20 %>
    </div>
    <div class="image-uploader">
      <a>カーソル位置に画像を挿入</a>
      <input class="image-uploader-input" id="image" type="file"></input>
    </div>

    <div class="field form-group">
      <%= f.text_field :tag, class: "form-control typeahead", placeholder:"タグ", autocomplete: "off" %>
    </div>

    <% if name == '作成' %>
    <%= collection_select :templates, :title, Report.where('tag LIKE ?', '%テンプレート%'), :id, :title, {:prompt => "テンプレート選択"}, class: 'form-control margin-bottom-md js-template-select' %>
    <% end %>

    <div class="field form-group">
      <%= f.label :attachments, '添付ファイル', class: 'label label-default' %>
      <span>(複数ファイル選択できます)</span>
      <%= f.file_field :attachments, id: "attachments", multiple: true, class: 'margin-top-sm form-control  ' %>
    </div>
    <div>
      <% @report.attachments.each do |a| %>
      <span class="nowrap">
        <%= a.name %>
        <%= link_to '削除', a, method: :delete, data: { confirm: '削除しますか?' }, class: "btn btn-warning btn-xs margin-right-md" %>
      </span>
      <% end %>
    </div>
  </div>
  <div class="field form-group form-inline">
    <%= f.hidden_field :user_id, :value => current_user.id %>
  </div>

  <div class="col-md-6">
    <div class="title-view" id="title-view"></div>
    <div class="content-view mode-edit" id="content-view"></div>
  </div>
</div>

<div class="bottom-action">
  <%= link_to '戻る', reports_path, class: "btn btn-default margin-right-md" %>
  <%= submit_tag '保存', class: "btn btn-primary" %>
  <span class="field form-group margin-left-sm">
    <%= f.check_box :collaboration, { id: "collaboration" }, "1", "0" %>共同編集
  </span>
</div>
<% end %>

app/views/reports/edit.html.erb
<%= render 'form', name: '更新' %>

app/views/reports/index.html.erb
<% if notice %>
<div id="notice" class="alert alert-success">
  <button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= notice %>
</div>
<% end %>

<%= link_to new_report_path, id: 'new-change', class: "new-report-change" do %>
  NEW
<% end %>

<div class="well">
  <span class="font-md margin-right-md">今月の人</span>
  <% @user_with_progress_points.first(3).each_with_index do |pp, i| %>
   <span class="label background-color-grade<%= i + 1 %> font-md margin-right-sm"><%= i + 1 %>位</span>
   <span class="font-lg"  ><%= pp.user_name %></span> さん
   <span class="badge margin-right-md"><%= pp.progress_points %></span>
  <% end %>
  <%= link_to progresses_path, class: "pull-right" do %>
    <i class="fa fa-line-chart fa-2x green-text"></i>
  <% end %>
  <%= link_to tagcloud_reports_path, class: "pull-right margin-right-md" do %>
    <i class="fa fa-cloud fa-2x gray-text"></i>
  <% end %>
</div>

<%= search_form_for @q, :html => {:class => "form-inline"} do |f| %>
  <%= f.text_field :tag_cont, :class => 'form-control typeahead', placeholder: 'タグ', autocomplete: "off" %>
  <%= f.text_field :title_cont, :class => 'form-control', placeholder: 'タイトル' %>
	<%= f.collection_select :user_id_eq, User.all, :id, :name, {:include_blank => true, :prompt => "ユーザー"}, class: 'form-control' %>
  <%= f.date_field :updated_at_gteq, :class => 'form-control' %>
  〜
  <% # http://qiita.com/LuckOfWise/items/e020e896e71d47d0c6a4 %>
  <%= f.date_field :updated_at_lteq_end_of_day, class: 'form-control', :value => 0.day.ago.strftime('%Y-%m-%d') %>
  <%= f.submit '検索', :class => 'btn btn-info margin-left-md' %>
<% end %>
<hr>

<%= page_entries_info @reports %>
<div class="table-responsive">
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th><i class="fa fa-star"></i></th>
        <th><%= sort_link(@q, :id, 'ID', default_order: :desc) %></th>
        <th><%= sort_link(@q, :progress_points, '成長', default_order: :desc) %></th>
        <th><%= sort_link(@q, :number_of_comments, 'コメント', default_order: :desc) %></th>
        <th><%= sort_link(@q, :tag, 'タグ') %></th>
        <th><%= sort_link(@q, :title, 'タイトル') %></th>
        <!-- <th><%= sort_link(@q, :user_name, '内容(1行目)') %></th> -->
        <th><%= sort_link(@q, :user_name, 'ユーザー') %></th>
        <th><%= sort_link(@q, 'attachments_name', '添付ファイル') %></th>
        <!-- <th>Created at</th> -->
        <th><%= sort_link(@q, :updated_at, '更新日時', default_order: :desc) %></th>
        <th>操作</th>
      </tr>
    </thead>

    <tbody>
      <%= hidden_field_tag('authenticity_token', form_authenticity_token) %>
      <% @reports.each do |report| %>
        <tr>
          <td>
            <div>
              <% if Favarite.where('report_id = ? AND user_id = ?', report.id, current_user.id).blank? %>
                <i class="fa fa-star lightgray-text" data-favarite = false data-report-id=<%= report.id %> ></i>
              <% else %>
                <i class="fa fa-star yellow-text" data-favarite = true data-favarite-id=<%= Favarite.where('report_id = ? AND user_id = ?', report.id, current_user.id).first.id %> data-report-id=<%= report.id %>></i>
              <% end %>
            </div>
          </td>
          <td><a class="clip" data-clipboard-text="" title="Click to copy me."><%= report.id %></a></td>
          <td><%= report.progress_points %></td>
          <td><%= report.number_of_comments %></td>
          <td><%= report.tag %></td>
          <!-- <td><%= link_to report.title, report %></td> -->
          <td><%= report.title %></td>
          <!-- <td><%= report.content.split[0] %></td> -->
          <td>
            <% unless report.user.nil? %>
            <%= report.user.name %>
            <% end %>
          </td>
          <td>
            <% report.attachments.each { |a| %>
            <%= a.name %><br>
            <% } %>
          </td>
          <!-- <td><%= report.created_at.strftime("%Y/%m/%d %H:%M") %></td> -->
          <td><%= report.updated_at.strftime("%Y/%m/%d %H:%M") %></td>
          <td>
            <%= link_to "参照", report %>
            <% if report.user_id == current_user.id || report.collaboration == 1 %>
              <%= link_to "更新", edit_report_path(report) %>
              <%= link_to '削除', report, method: :delete, data: { confirm: '削除しますか?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @reports %>

<!-- <%= link_to new_report_path, id: 'new', class: "new-report" do %>
  <span class="font-xlg">新</span>しい<div class="margin-left-md"><span class="font-lg">R</span>eport</div>
<% end %> -->

app/views/reports/new.html.erb
<%= render 'form', name: '作成' %>
<%= javascript_include_tag :templates %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<div class="text-right">
  <%= link_to 'スライドモード', slide_path, class: "btn btn-info margin-right-md", :target => "_blank" %>
  <% if @report.user_id == current_user.id || @report.collaboration == 1 %>
  <%= link_to '更新', edit_report_path(@report), class: "btn btn-primary margin-right-md"  %>
  <%= link_to '削除', @report, method: :delete, data: { confirm: '削除しますか?' }, class: "btn btn-warning" %>
  <% end %>
</div>

<div class="margin-bottom-sm">
  <span class="label label-default">タグ</span>
  <% @report.tag.split(",").each { |tag| %>
  <%= tag %>
<% } %>
<span>
  <span class="label label-default">ユーザー</span>
  <% unless @report.user.nil? %>
  <%= @report.user.name %>
  <% end %>
</span>
<span>
  <span class="label label-default">作成日時</span>
  <%= @report.created_at.strftime("%Y/%m/%d %H:%M") %>
</span>
<span>
  <span class="label label-default">更新日時</span>
  <%= @report.updated_at.strftime("%Y/%m/%d %H:%M") %>
</span>
</div>

<div class="content-flex">
  <div class="content-index">
    <div class="content-nav"></div>
  </div>
  <div class="content-body">
      <div id="title-view" class="title-view">
      <%= @report.title %>
      </div>

      <div class="content-view" id="content-view">
          <%= @report.content %>
      </div>

      <div>
      <% if @report.attachments.presence %>
      <% @report.attachments.each do |a| %>
      <span class="nowrap">
        <%= a.name %>
        <%= link_to 'ダウンロード', { action: :download, id: a[:id] }, class: 'btn btn-default btn-xs margin-right-md' %>
      </span>
      <% end %>
      <% end %>
      </div>

      <div class=" background-color-lightgreen padding-sm">
      <span class="label label-success">コメント</span>
      <div class="row">
        <div class="col-md-6 comments">
          <% @report.comments.each do |c| %>
          <div class="comment">
            <span class="time"><%= c.updated_at.strftime("%Y/%m/%d %H:%M") %></span>
            <span class="name"><%= c.user.name %></span>
            <span><%= auto_link(simple_format(h(c.comment))) %></span>
          </div>
          <% end %>
        </div>
        <div class="col-md-6">
          <%= form_tag('/comments', :method => :post) do %>
          <div class="field form-group">
            <%= text_area :comment, :comment, class: "form-control", placeholder: "コメントする..." %>
            <%= hidden_field :comment, :report_id, value: @report.id %>
            <%= hidden_field :comment, :user_id, value: current_user.id %>
            <%= submit_tag "送信", class: "btn btn-sm btn-default margin-top-sm" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="bottom-action">
<%= link_to '戻る', reports_path, class: "btn btn-default pull-left margin-right-md" %>
<% if @report.user_id != current_user.id %>
<%= link_to progresses_path( progress: {point:1, report_id:@report.id, user_id:current_user.id} ), method: :post, class: 'like like-active', title: '「成長したね」と思ったらクリック！' do %>
<i class="fa fa-heart"></i>
<span class="like-count"><%= @report.progresses.map{|item| item.point}.sum %></span>
<% end %>
<% else %>
<div class="like">
  <i class="fa fa-heart"></i>
  <span class="like-count"><%= @report.progresses.map{|item| item.point}.sum %></span>
</div>
<% end %>
<!-- <div class="arrow-box pull-left"><%= @report.progresses.map{|item| item.point}.sum %></div> -->
</div>

app/views/reports/slide.html.erb
<textarea id="source">
  <%= @report.content %>
</textarea>
<%= javascript_include_tag :slide %>

app/views/reports/tagcloud.erb
<%= javascript_include_tag :tagcloud %>
<div id="tagcloud" style="width: 800px; height: 600px;">...</div>