config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :favarites

  root to: 'reports#index'
  devise_scope :user do
    get '/users/sign_up' => 'users#sign_up', as: :users_sign_up
    post 'users/admin_create' => 'users#admin_create', :as => 'user_admin_create'
  end
  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :users do
    collection do
      get 'with_progresses'
    end
  end

  resources :reports do
    collection do
      get 'tagcount'
      get 'tagcloud'
    end
  end
  resources :reports
  get 'reports/download/:id'=> 'reports#download', as: :donwload
  get 'reports/:id/slide'=> 'reports#slide', as: :slide

  resources :attachments
  resources :images
  get 'images/show/:id'=> 'images#show', as: :show_image
  resources :comments do
    collection do
      get 'for_user/:user_id' => 'comments#for_user', as: :for_user
      get 'back_for_user/:user_id' => 'comments#back_for_user', as: :back_for_user
    end
  end
  resources :comments
  resources :progresses do
    collection do
      get 'for_user/:user_id' => 'progresses#for_user', as: :for_user
    end
  end
  resources :progresses
  post 'notices/upsert' => 'notices#upsert', as: :upsert
  resources :notices

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>ProgressReport</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'common' %>
          <%= javascript_include_tag params[:controller] %>
            <%= csrf_meta_tags %>

              <!-- Bootstrap -->
              <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
              <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
              <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
  </head>

  <body>
    <header>
      <div id="user_id" class="hidden">
        <% if user_signed_in? %>
          <%= current_user.id %>
            <% end %>
      </div>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to 'Progress Report', '/reports', :class => 'navbar-brand' %>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
              <li>
                <%= link_to events_path, class: 'header-icon' do %>
                  <i class="fa fa-calendar fa-lg white-text"></i>
                  <% end %>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
                <li class="header-icon">
                  <i id="notice" class="fa fa-bell fa-lg lightgray-text" data-toggle="modal" data-target="#myModal"></i>
                </li>
                <li>
                  <%= link_to favarites_path, class: 'header-icon' do %>
                    <i class="fa fa-star fa-lg yellow-text"></i>
                    <% end %>
                </li>
                <li class="loginuser">
                  <span id="user_name">
                    <%= current_user.name %>
                  </span> さん
                </li>
                <li>
                  <%= link_to edit_user_registration_path do %>
                    <i class="fa fa-cog fa-lg white-text"></i>
                    <% end %>
                </li>
                <% if current_user.admin? %>
                  <li>
                    <%= link_to users_sign_up_path do %>
                      <i class="fa fa-meh-o fa-lg white-text"></i>
                      <% end %>
                  </li>
                  <% end %>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-sign-out fa-lg white-text"></i>
                        <% end %>
                    </li>
                    <% else %>
                      <li>
                        <%= link_to "ログイン", new_user_session_path %>
                      </li>
                      <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <p class="notice">
      <%= notice %>
    </p>
    <p class="alert">
      <%= alert %>
    </p>
    <div class="container">
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <div id="notice-body" class="margin-top-lg"></div>
            </div>
          </div>
        </div>
      </div>
      <%= yield %>
        <footer>
          <hr>
          <ul>
            <li>&copy; 2015
              <%= link_to 'itagakishintaro', 'https://github.com/itagakishintaro', target: '_blank' %> &
                <%= link_to 'uedatakeshi', 'https://github.com/uedatakeshi', target: '_blank' %>
            </li>
            <li>·</li>
            <li>
              <%= link_to 'GitHub', 'https://github.com/itagakishintaro/ProgressReport', target: '_blank' %>
            </li>
            <li>·</li>
            <li>
              <%= link_to 'Bugs & Requests', 'https://github.com/itagakishintaro/ProgressReport/issues', target: '_blank' %>
            </li>
          </ul>
        </footer>
    </div>
    <!-- /.container -->

  </body>

</html>

app/views/layouts/slide.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProgressReport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
	<%= yield %>
</body>
</html>